<a href="https://colab.research.google.com/github/Y00NSJ/CV-DL/blob/main/numpy/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print("배열의 차원 : ", arr.ndim)
print("배열의 형태 : ", arr.shape)
print("배열의 데이터 타입 : ", arr.dtype)
print()


a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("요소 덧셈 결과 : ", a + b)
print("배열 a의 모든 원소 제곱 결과 : ", a ** 2)
print("배열 b의 평균값 : ", b.mean())
print()


arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])
print(arr[1, 1])
print(arr[0])
print(arr[:, 1])
print()


arr = np.array([10, 15, 20, 25, 30, 35])
print(arr[arr > 20])
arr[arr >= 30] = 0
print(arr)
print()


arr1 = np.arange(10)
print("0-9 정수 1차원 배열 : ", arr1)
arr2 = np.eye(3, dtype=int)
print("3*3 단위행렬 : \n",arr2)
arr3 = np.random.randint(0, 10, 5)
print("정렬 전 : ", arr3)
print("정렬 후 : ", np.sort(arr3))




A = np.arange(9.).reshape(3,3)   # (3,3) 2d array
x = np.array([2,0,1])             # (3,)  1d array
y = x.reshape(1,3)                # (1,3) 2d array
z = x.reshape(3,1)

print(np.matmul(A,z))   # (3,3)*(3,1) -> (3,1)
print(np.matmul(A,x))   # (3,3)*(3,) -> (3,)   # x의 차원이 (3,1)이 되었다가 계산 후 (3,)으로 축소

배열의 차원 :  2
배열의 형태 :  (2, 3)
배열의 데이터 타입 :  int64

요소 덧셈 결과 :  [5 7 9]
배열 a의 모든 원소 제곱 결과 :  [1 4 9]
배열 b의 평균값 :  5.0

50
[10 20 30]
[20 50 80]

[25 30 35]
[10 15 20 25  0  0]

0-9 정수 1차원 배열 :  [0 1 2 3 4 5 6 7 8 9]
3*3 단위행렬 : 
 [[1 0 0]
 [0 1 0]
 [0 0 1]]
정렬 전 :  [2 1 1 1 0]
정렬 후 :  [0 1 1 1 2]
[[ 2.]
 [11.]
 [20.]]
[ 2. 11. 20.]
